export type IconT =
    "about" |
    "account" |
    "add" |
    "appearance" |
    "arrowRight" |
    "back" |
    "brush" |
    "checkmark" |
    "closeWindow" |
    "copy" |
    "file" |
    "history" |
    "home" |
    "identification" |
    "link" |
    "lock" |
    "logout" |
    "minimizeWindow" |
    "nearbyShare" |
    "receive" |
    "remove" |
    "reset" |
    "send" |
    "settings" |
    "sidebar" |
    "stopwatch" |
    "sync" |
    "updates" |
    "upload" |
    "warning" |
    "wifiOff";