export type IconType = 
    "home" |
    "send" |
    "receive" |
    "settings" |
    "account" |
    "chevron" |
    "files" |
    "add" |
    "remove" |
    "copy" |
    "link" |
    "check" |
    "accountRecovery" |
    "accountCreate" |
    "accountSuccess" |
    "email" |
    "dismiss" |
    "sync" |
    "history" |
    "history-bold" |
    "editAccount" |
    "logout" |
    "warning" |
    "user" |
    "accountDelete" |
    "lock" |
    "appearance" |
    "nearbyShare" |
    "updates" |
    "reset" |
    "about" |
    "offline";